CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    email VARCHAR(150) NOT NULL
        CONSTRAINT UK_EMAIL_USER UNIQUE,
    name  VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    name VARCHAR(50) NOT NULL
        CONSTRAINT uk_name_categories
            UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    annotation         VARCHAR(2000)               NOT NULL,
    confirmed_requests BIGINT                      NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000)               NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    desc_location      VARCHAR(255),
    lat                REAL                        NOT NULL,
    lon                REAL                        NOT NULL,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                     NOT NULL,
    state              INTEGER                     NOT NULL,
    title              VARCHAR(100)                NOT NULL,
    views              BIGINT,
    categories_id      BIGINT                      NOT NULL
        CONSTRAINT fk_event_categories_id
            REFERENCES categories,
    initiator_id       BIGINT                      NOT NULL
        CONSTRAINT fk_event_user_id
            REFERENCES users
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    created      TIMESTAMP WITH TIME ZONE NOT NULL,
    status       INTEGER                  NOT NULL,
    event_id     BIGINT                   NOT NULL
        CONSTRAINT fk_request_event_id
            REFERENCES events,
    requester_id BIGINT                   NOT NULL
        CONSTRAINT fk_requester_id
            REFERENCES users
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT NOT NULL
        CONSTRAINT fk_events_compilations_compilation_id REFERENCES compilations (id) ON DELETE CASCADE,
    events_id      BIGINT NOT NULL UNIQUE
        CONSTRAINT fk_events_compilations_event_id REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, events_id)
);
CREATE INDEX IF NOT EXISTS fk_events_compilations_compilation_id ON compilations_events (compilation_id);
CREATE INDEX IF NOT EXISTS fk_events_compilations_event_id ON compilations_events (events_id);

CREATE TABLE IF NOT EXISTS comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    date_create TIMESTAMP     NOT NULL,
    date_edit   TIMESTAMP,
    edited      BOOLEAN,
--     eventState  INTEGER,
    text        VARCHAR(2000) NOT NULL,
    author_id   BIGINT        NOT NULL
        CONSTRAINT fk_comment_user
            REFERENCES users,
    event_id    BIGINT        NOT NULL
        CONSTRAINT fk_comment_event
            REFERENCES events
);

ALTER TABLE users
    OWNER TO ewmroot;
ALTER TABLE categories
    OWNER TO ewmroot;
ALTER TABLE events
    OWNER TO ewmroot;
ALTER TABLE requests
    OWNER TO ewmroot;
ALTER TABLE compilations
    OWNER TO ewmroot;
ALTER TABLE compilations_events
    OWNER TO ewmroot;
ALTER TABLE comments
    OWNER TO ewmroot;