-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(500)                            NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    annotation         VARCHAR(1000)                           NOT NULL,
    description        VARCHAR(5000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    lat                REAL                                    NOT NULL,
    lon                REAL                                    NOT NULL,
    categories_id      BIGINT                                  NOT NULL
        CONSTRAINT fk_events_categories_id REFERENCES categories (id) ON DELETE CASCADE,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  BIGINT,
    initiator_id       BIGINT                                  NOT NULL
        CONSTRAINT fk_events_initiator_id REFERENCES users (id) ON DELETE CASCADE,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                 NOT NULL,
    state              VARCHAR(50)                             NOT NULL,
    confirmed_requests BIGINT                                  NOT NULL,
    views              BIGINT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS fk_events_category_id ON events (categories_id);
CREATE INDEX IF NOT EXISTS fk_events_initiator_id ON events (initiator_id);

-- Таблица подборок событий
CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id BIGINT NOT NULL
        CONSTRAINT fk_events_compilations_compilation_id REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL
        CONSTRAINT fk_events_compilations_event_id REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id)
);
CREATE INDEX IF NOT EXISTS fk_events_compilations_compilation_id ON events_compilations (compilation_id);
CREATE INDEX IF NOT EXISTS fk_events_compilations_event_id ON events_compilations (event_id);

CREATE TABLE IF NOT EXISTS requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      timestamp WITHOUT TIME ZONE             NOT NULL,
    event_id     bigint                                  NOT NULL
        CONSTRAINT fk_requests_event_id REFERENCES events (id) ON DELETE CASCADE,
    requester_id bigint                                  NOT NULL
        CONSTRAINT fk_requests_requester_id REFERENCES users (id) ON DELETE CASCADE,
    status       varchar(50)                             NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS fk_requests_event_id ON requests (event_id);
CREATE INDEX IF NOT EXISTS fk_requests_requester_id ON requests (requester_id);







