version: '3.1'
services:
  stats-server:
    build: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:pool:postgresql://stats-db:5432/EwmStatsDb?encoding=utf8
      - SPRING_DATASOURCE_USERNAME=statsroot
      - SPRING_DATASOURCE_PASSWORD=statsroot

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=EwmStatsDb
      - POSTGRES_USER=statsroot
      - POSTGRES_PASSWORD=statsroot

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - stats-db
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/EwmMainDb
      - SPRING_DATASOURCE_USERNAME=ewmroot
      - SPRING_DATASOURCE_PASSWORD=ewmroot

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=EwmMainDb
      - POSTGRES_USER=ewmroot
      - POSTGRES_PASSWORD=ewmroot