-- Таблица EndPoints
CREATE TABLE IF NOT EXISTS ENDPOINTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(100)                            NOT NULL,
    uri       VARCHAR(100)                            NOT NULL,
    uri_id    VARCHAR(100),
    ip        VARCHAR(50)                             NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE             NOT NULL
);